const app = Vue.createApp({
    data() {
        return {
            jobs: [
                {
                    img: "https://media.licdn.com/dms/image/C4D0BAQEdRuehGN2rGQ/company-logo_100_100/0/1633369276620/domain_technology_partners_logo?e=1707350400&v=beta&t=eublF2aKFxd4MjuvsNXb0A-KewCIsx8GV45Ar1oPqwY",
                    alt: "Integris-Logo",
                    company: "Integris",
                    title: "PMO Solutions Architect",
                    status: "Full-time",
                    location: "Austin, Texas Metropolitan Area",
                    office: "Remote",
                    details: [
                        "Design & deployed Azure networks",
                        "Design & deployed hybrid connectivity (Azure VPN Gateway, 3rd party NVA's)",
                        "Primary technical resource for server and network migrations",
                    ],
                    skills: [
                        "Network Administration",
                        "Azure Networking",
                        "Cisco Networking",
                        "Windows Server",
                        "VMware",
                        "Microsoft 365",
                    ],
                },
                {
                    img: "/img/caltech.png",
                    alt: "Caltech-Logo",
                    company: "CalTech Software Systems",
                    title: "Project Engineer III",
                    status: "Full-time",
                    location: "Austin, Texas Metropolitan Area",
                    office: "Remote",
                    details: [
                        "Lead engineer on new customer onboardings",
                        "Lead engineer on server migrations to the CalTech datacenter",
                        "Senior technical resource for project engineers",
                        "Migrated core banking routers to the CalTech datacenter",
                        "Network upgrades deploying Cisco routers, switches, and firewalls",
                        "Windows server migrations from 2008/2012 to server 2019",
                        "Deployed, documented, and created standard processes around CalTech's new cybersecurity product",
                    ],
                    skills: [
                        "Network Administration",
                        "Azure Networking",
                        "Cisco Networking",
                        "Windows Server",
                        "VMware",
                        "Microsoft 365",
                    ],
                },
                {
                    img: "/img/caltech.png",
                    alt: "CalTech-Logo",
                    company: "CalTech Software Systems",
                    title: "Project Engineer II",
                    status: "Full-time",
                    location: "Austin, Texas Metropolitan Area",
                    office: "Onsite",
                    details: [
                        "Scoped and priced client projects and exceeded target efficiency by 6%",
                        "Surpassed yearly revenue goal",
                        "Executed server 2008 to server 2019 migrations",
                        "Performed network upgrades including Cisco 2960 and 9200 series switches, Cisco ISR 4000 series routers, - Cisco ASA 5506, Cisco Call Manager Express, Cisco Meraki access points and switches, and Cisco AnyConnect VPN",
                        "Planned and executed new site turn ups",
                        "Migrated core banking routers to the CalTech datacenters",
                        "Upgraded ATMs and ATM network equipment",
                        "Configured Microsoft MDT Server to facilitate mass Windows 10 deployments",
                        "Installed and upgraded VMWare ESXi versions 5.x, 6.x, and 7.x including SAN implementations",
                        "Migrated clients from Exchange 2013/2016 to Office 365",
                        "Configured Office 365 for DMARC email security",
                        "Migrated clients between email filter and email encryption solutions",
                        "Deployed Microsoft Intune MDM for mobile device and mobile app management",
                        "Built Azure Conditional Access rules securing access to Azure and Office 365",
                    ],
                    skills: [
                        "Network Administration",
                        "Cisco Networking",
                        "Windows Server",
                        "VMware",
                        "Microsoft 365",
                    ],
                },
                {
                    img: "/img/caltech.png",
                    alt: "CalTech-Logo",
                    company: "CalTech Software Systems",
                    title: "Tier II Engineer",
                    status: "Full-time",
                    location: "Austin, Texas Metropolitan Area",
                    office: "Onsite",
                    details: [
                        "Provide support and resolutio for Priority 1 issues",
                        "Escalation point for helpdesk tickets",
                        "Documented customer networks and tested critical backup infrastructure",
                        "Migrated email filtering services from on premise Linux appliances to Zix cloud-based encryption",
                        "Migrated email filtering services from on Sophos Reflexion to Zix cloud-based filter",
                    ],
                    skills: ["Windows Server", "VMware", "Microsoft 365"],
                },
                {
                    img: "/img/caltech.png",
                    alt: "CalTech-Logo",
                    company: "CalTech Software Systems",
                    title: "Tier I Engineer",
                    status: "Full-time",
                    location: "Austin, Texas Metropolitan Area",
                    office: "Onsite",
                    details: [
                        "Provided first line of support for customers and internal staff",
                        "Resolved break/fix issues with a priority placed upon customer service, perception, and satisfaction",
                        "Created and updated knowledge base articles with issue resolution and created documentation for software installation and upgrades",
                        "Applied working knowledge of policies and procedures, determining the best course of action to resolve issues according to service-level objectives",
                        "anaged workstation upgrades for multiple projects, installing hardware, software, and peripherals, and provided onsite support for clients in the greater Austin area",
                        "Assisted new team members with technical issues, workflow, and proper escalation procedures",
                    ],
                    skills: [
                        "Windows 10",
                        "Windows Server",
                        "Microsoft 365",
                        "Desktop Support",
                    ],
                },
                {
                    img: "https://media.licdn.com/dms/image/D560BAQGs1CBbJ5vMPA/company-logo_100_100/0/1663676834577/baesystemsinc_logo?e=1707350400&v=beta&t=yGRBpRbgkStjegmUULTDTZybJotmIqLyt5tLgbqjR6Q",
                    alt: "BAE Systems Logo",
                    company: "BAE Systems",
                    title: "Tech Intern II",
                    status: "Full-time",
                    location: "Hudson, New Hampshire",
                    office: "Onsite",
                    details: [
                        "Supported Engineering Tools group, handling break/fix tickets in Remedy and tested applications in Windows 10 ahead of Windows 7 to Windows 10 upgrades",
                        "Converted internal web-based applications from self-signed certificates to Active Directory PKI, including IBM Apache server",
                    ],
                    skills: ["Windows 10", "Desktop Support"],
                },
                {
                    img: "https://media.licdn.com/dms/image/D560BAQGs1CBbJ5vMPA/company-logo_100_100/0/1663676834577/baesystemsinc_logo?e=1707350400&v=beta&t=yGRBpRbgkStjegmUULTDTZybJotmIqLyt5tLgbqjR6Q",
                    alt: "BAE Systems Logo",
                    company: "BAE Systems",
                    title: "Tech Intern I",
                    status: "Full-time",
                    location: "Merrimack, New Hampshire",
                    office: "Onsite",
                    details: [
                        "Provided helpdesk first line of support for end users, handling break/fix tickets in Remedy for software applications and hardware issues",
                        "Performed desktop upgrades, inventory management, and printer support for multiple sites",
                    ],
                    skills: ["Windows 10", "Desktop Support"],
                },
            ],
        };
    },
});

app.mount("#app");
